/* USER ACTIONS */
export const USER_ACTION_START = 'USER_ACTION_START';
export const USER_ACTION_FAILURE = 'USER_ACTION_FAILURE';

//  create a user
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_AUTO = 'CREATE_USER_AUTO';

// remove a user
export const REMOVE_USER = 'REMOVE_USER';

/* LOBBY ACTIONS */
export const LOBBY_ACTION_FAILURE = 'LOBBY_ACTION_FAILURE';
export const LOBBY_ACTION_START = 'LOBBY_ACTION_START';

// create a lobby
export const CREATE_LOBBY_SUCCESS = 'CREATE_LOBBY_SUCCESS';

// join a lobby
export const JOIN_LOBBY_SUCCESS = 'JOIN_LOBBY_SUCCESS';
