/* USER ACTIONS */
export const USER_ACTION_START = 'USER_ACTION_START';
export const USER_ACTION_FAILURE = 'USER_ACTION_FAILURE';

//  create a user
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_AUTO = 'CREATE_USER_AUTO';

// remove a user
export const REMOVE_USER = 'REMOVE_USER';

/* ROOM ACTIONS */
export const ROOM_ACTION_FAILURE = 'ROOM_ACTION_FAILURE';
export const ROOM_ACTION_START = 'ROOM_ACTION_START';

// create a room
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';

// join a room
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';

/* LOBBY ACTIONS */
export const LOBBY_ACTION_FAILURE = 'LOBBY_ACTION_FAILURE';
export const LOBBY_ACTION_START = 'LOBBY_ACTION_START';

// join a team
export const JOIN_TEAM_SUCCESS = 'JOIN_TEAM_SUCCESS';
